// Version and build ID injected at build time by next.config.ts.
// Do NOT edit this file — configure versioning in src/app/_config/owner.ts instead.
// NEXT_PUBLIC_OS_VERSION  → the semver string  (e.g. "1.2.3")
// NEXT_PUBLIC_OS_BUILD_ID → the short Git SHA  (e.g. "a1b2c3d")
export const OS_VERSION  = process.env.NEXT_PUBLIC_OS_VERSION  ?? "0.0.0";
export const OS_BUILD_ID = process.env.NEXT_PUBLIC_OS_BUILD_ID ?? "unknown";
